########################################
# 基本配置
########################################
theme_version_check: true
theme_config_check: true
# 主選單導航
# 更多圖標資訊，請訪問 https://github.com/D-Sketon/hexo-theme-reimu/issues/30
menu:
  - name: home
    url: /
    icon:
  - name: archives
    url: /archives
    icon:
  - name: about
    url: /about
    icon:
  - name: friend
    url: /friend
    icon:

banner: "/img/banner.webp"

# 如果您想使用 srcset 屬性，請啟用它
banner_srcset:
  enable: true
  srcset:
    - src: "/img/banner-600w.webp"
      media: "(max-width: 479px)"
    - src: "/img/banner-800w.webp"
      media: "(max-width: 799px)"
    - src: "/img/banner.webp"
      media: "(min-width: 800px)"

favicon: "/images/favicon.ico"

avatar: "avatar.webp" 

# Open Graph
# 參見 https://hexo.io/docs/helpers#open-graph
open_graph:
  enable: true
  options:
    default_og_image: /img/banner.webp 

# 內容
excerpt_link: 閱讀更多

# RSS
# 需要 https://github.com/hexojs/hexo-generator-feed
rss: atom.xml

# 一個非常簡單的替代方案，適用於 https://hexo.io/api/injector
injector:
  head_begin: # 在 <head> 後注入代碼片段
  head_end: # 在 </head> 前注入代碼片段
  body_begin: # 在 <body> 後注入代碼片段
  body_end: |
    <script>
      console.log('Footer loaded');
    </script>
  sidebar_begin: # 在 <aside> 後注入代碼片段
  sidebar_end: # 在 </aside> 前注入代碼片段

footer:
  since: 2025 
  powered: true
  count: true # 顯示字數和閱讀時間
  busuanzi: false
  icon:
    url: "../images/taichi.png" # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾
    rotate: true
    mask: true
    color: "#0000FF" # 確保設置為藍色

# 側邊欄
sidebar: left

social:
  email: mailto:kuoray333@gmail.com
  github: https://github.com/itousouta15
  instagram: https://www.instagram.com/itou.souta15
  discord: https://discord.gg/GVhwRRVJ7F

widgets:
  - category
  - tag
  - archive
  - recent_posts

# Widget 行為
archive_type: "每月"
show_count: false
recent_posts_limits: 5

i18n:
  enable: true
  languages:
    - zh-TW
    - en
########################################
# CSS
########################################
anchor_icon: f0c1

reimu_cursor:
  enable: true
  cursor:
    default: ../img/cursor/1.png  # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾
    pointer: ../img/cursor/2.png
    text: ../img/cursor/3.png

# 設置為 false 以啟用 fontawesome
icon_font: false

# Google 字體，優先於本地字體
font:
  article:
    - Mulish
  #  - Noto Serif SC
  code:
    - Ubuntu Mono
  #  - Source Code Pro
  #  - JetBrains Mono

# 本地備選字體
local_font:
  article:
    - "-apple-system"
  #  - PingFang SC
  #  - Microsoft YaHei
  #  - sans-serif
  code:
  #  - Menlo
  #  - Monaco
  #  - Consolas
  #  - monospace

dark_mode:
  # true 表示默認啟用深色模式
  # false 表示默認禁用深色模式
  # auto 表示根據系統設置自動切換深色模式
  enable: ture # true | false | auto

# 需要 https://github.com/D-Sketon/hexo-renderer-markdown-it-plus
markdown:
  container: false # 是否啟用容器樣式

########################################
# Markdown 顯示
########################################

# 需要 https://github.com/D-Sketon/hexo-renderer-markdown-it-plus
math:
  enable: true 
  katex:
    enable: false
    autoRender: true 
  mathjax:
    enable: true
    options: # 參見 https://docs.mathjax.org/en/latest/web/configuration.html
      {
        tex: {
          tags: "ams",
          useLabelIds: true,
          inlineMath: [["$", "$"], ['\\(', '\\)']],
          displayMath: [["$$", "$$"], ['\\[', '\\]']],
          processEscapes: true,
          processEnvironments: true,
          autoload: { color: [], colorv2: ["color"] },
          packages: { "[+]": ["noerrors"] },
        },
        options:
          {
            skipHtmlTags:
              ["script", "noscript", "style", "textarea", "pre", "code"],
            ignoreHtmlClass: "tex2jax_ignore",
            processHtmlClass: "tex2jax_process",
          },
        loader: { load: ["input/asciimath", "[tex]/noerrors"] },
      }

# mermaid 圖表 https://github.com/knsv/mermaid
# 需要 https://github.com/webappdevelp/hexo-filter-mermaid-diagrams
mermaid:
  enable: true

code_block:
  expand: true

##########################################################
# 分析
##########################################################

baidu_analytics: false
google_analytics: false
clarity: false

########################################
# 評論系統
########################################

waline:
  enable: true # 修正拼寫錯誤
  serverURL: https://web-eight-weld-65.vercel.app
  lang: zh-TW
  locale: {} # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80
  emoji:
    - https://unpkg.com/@waline/emojis@1.2.0/weibo
    - https://unpkg.com/@waline/emojis@1.2.0/alus
    - https://unpkg.com/@waline/emojis@1.2.0/bilibili
    - https://unpkg.com/@waline/emojis@1.2.0/qq
    - https://unpkg.com/@waline/emojis@1.2.0/tieba
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  meta:
    - nick
    - mail
    - link
  requiredMeta:
    - nick
    - mail
  wordLimit: 0
  pageSize: 10
  pageview: true

########################################
# 搜索
########################################

# 需要 https://github.com/D-Sketon/hexo-algoliasearch
# 請在您的 _config.yml 中添加以下配置
algolia:
  appId: 'your_application_id' # 替換為您的 Algolia 應用 ID
  apiKey: 'your_search_only_api_key' # 替換為您的 Algolia 搜索 API 密鑰
  indexName: 'your_index_name' # 替換為您的索引名稱
# algolia:
#   appId: 'your applicationID'
#   apiKey: 'your apiKey'
#   adminApiKey: 'your adminApiKey'
#   indexName: 'your indexName'
#   chunkSize: 5000
#   fields:
#     - content:strip:truncate,0,500
#     - excerpt:strip
#     - gallery
#     - permalink
#     - photos
#     - slug
#     - tags
#     - title
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: "搜索....."
    hits_empty: "未發現與 「${query}」相關內容"
    hits_stats: "找到${hits}條結果（用時 ${time} ms）"

generator_search:
  enable: false
  field: post
  content: true

########################################
# 動畫
########################################

# 加載動畫
preloader:
  enable: true
  text: 載入中...
  icon:
    url: "../images/taichi.png" # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾

# 參見 https://github.com/D-Sketon/aos.js
animation:
  enable: true
  options:
    header:
      title: slide-up
      subTitle: slide-down
    home:
      post: fade-up
      widget: fade-up
      sidebar: fade-up
    article:
      whole: fade-up
      date: zoom-in
      category: zoom-in
      tag: zoom-in
      comment: zoom-in
      reading: zoom-in
      nav: fade-up
    archive:
      whole: fade-up
      tag: zoom-in
      category: zoom-in
      section: fade-up
      nav: fade-up

# 參見 https://github.com/D-Sketon/mouse-firework
firework:
  enable: true
  options:
    excludeElements: ["a", "button"]
    particles:
      - shape: circle
        move: ["emit"]
        easing: easeOutExpo
        colors: ['#FBC2EB', '#A6C1EE', '#FDCDE5', '#D4FC79'] # 更淡的藍色漸變效果
        number: 20
        duration: [1200, 1800]
        shapeOptions:
          radius: [16, 32]
          alpha: [0.3, 0.5]
      - shape: circle
        move: ["diffuse"]
        easing: easeOutExpo
        colors: ["#ADD8E6"] # 純淺藍色
        number: 1
        duration: [1200, 1800]
        shapeOptions:
          radius: 20
          alpha: [0.2, 0.5]
          lineWidth: 6

########################################
# 擴展功能
########################################

# 剪貼板配置
clipboard:
  success: 複製成功(*^▽^*)
  fail: 複製失敗(ﾟ⊿ﾟ)ﾂ
  copyright: # 是否為剪貼內容添加版權
    enable: true
    count: 50 # 顯示版權時的字符數
    content: 本文版權：本部落格所有文章除特別聲明外，均使用 BY-NC-SA 許可協議。轉載請註明出處！

# 在首頁顯示分類卡片
home_categories:
  enable: false
  content:
    - categories: hexo # 字符串（單層分類）或數組（多層分類）
      cover:  # 空表示隨機封面

# 是否在文章過期時顯示通知
outdate:
  enable: true
  daysAgo: 180 # 文章被認為過期的天數
  message: 本文最后更新于 {time}，请注意文中内容可能已经发生变化。

# 贊助
sponsor:
  enable: false
  tip: 请作者喝杯咖啡吧！
  icon:
    url: "../images/taichi.png" # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾
    rotate: true
    mask: true # 是否將圖片用作遮罩
  qr:
    # - name: 支付宝
    #   src: "/sponsor/alipay.jpg"
    # - name: 微信
    #   src: "/sponsor/wechat.png"

# 在每篇文章下顯示版權
article_copyright:
  enable: true
  content:
    author: true
    link: true
    title: false
    date: false
    updated: false
    license: true

# 返回頂部
top:
  enable: true
  position: right # left or right
  icon:
    url: "../images/taichi.png" # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾
    rotate: true
    mask: true # 是否將圖片用作遮罩
    color: "#0000FF" # 確保設置為藍色

share:
  # - facebook
  # - twitter
  # - linkedin
  # - reddit
  # - weibo
  # - qq
  # - weixin

########################################
# 實驗性功能
########################################

# 實驗性功能，可能有很多錯誤，請謹慎開啟！
pjax:
  enable: false

# 實驗性功能
# https://github.com/GoogleChromeLabs/quicklink
quicklink:
  enable: false
  # `requestIdleCallback` 的超時時間，以毫秒為單位。
  timeout: 3000
  # 是否應將 options.el 容器內的 URL 視為高優先級。
  priority: true
  # 確定是否應預取 URL。
  # 僅支持字符串
  ignores: []

# https://github.com/CodeByZach/pace
pace:
  enable: true

# 實驗性功能
service_worker:
  enable: true

# 實驗性功能
live2d:
  enable: false
  position: left # left or right

# 實驗性功能
# 請開啟 pjax 以使用此功能
live2d_widgets:
  enable: false

# 實驗性功能
player:
  # 如果您啟用了 meting，您必須先啟用 aplayer
  aplayer:
    # https://github.com/DIYgod/APlayer
    enable: false
    options:
      audio:
      fixed:
      autoplay:
      loop:
      order:
      preload:
      volume:
      mutex:
      listFolded:
      lrcType:
  meting:
    # https://github.com/metowolf/MetingJS
    # 如果您想使用 meting，請先啟用 aplayer
    enable: false
    meting_api: # 自定義 api
    options:
      id: 2265921590
      server: netease
      type: playlist

########################################
# 供應商
########################################

# 依賴 cdn 連結
# 如果您更改了 js 庫的版本，請務必修改相應的完整性值
vendor:
  cdn_jsdelivr_gh: https://cdn.jsdelivr.net/gh/
  cdn_jsdelivr_npm: https://cdn.jsdelivr.net/npm/
  fastly_jsdelivr_gh: https://fastly.jsdelivr.net/gh/
  fastly_jsdelivr_npm: https://fastly.jsdelivr.net/npm/
  unpkg: https://unpkg.com/
  webcache: https://npm.webcache.cn/
  js:
    clipboard:
      src: webcache|clipboard@2.0.11/dist/clipboard.min.js
      integrity: sha384-J08i8An/QeARD9ExYpvphB8BsyOj3Gh2TSh1aLINKO3L0cMSH2dN3E22zFoXEi0Q
    lazysizes:
      src: webcache|lazysizes@5.3.2/lazysizes.min.js
      integrity: sha384-3gT/vsepWkfz/ff7PpWNUeMzeWoH3cDhm/A8jM7ouoAK0/fP/9bcHHR5kHq2nf+e
    photoswipe:
      src: webcache|photoswipe@5.4.4/dist/photoswipe.esm.min.js
      integrity: sha384-WkkO3GCmgkC3VQWpaV8DqhKJqpzpF9JoByxDmnV8+oTJ7m3DfYEWX1fu1scuS4+s
    photoswipe_lightbox:
      src: webcache|photoswipe@5.4.4/dist/photoswipe-lightbox.esm.min.js
      integrity: sha384-DiL6M/gG+wmTxmCRZyD1zee6lIhawn5TGvED0FOh7fXcN9B0aZ9dexSF/N6lrZi/
    valine:
      src: webcache|valine@1.5.1/dist/Valine.min.js
      integrity: sha384-3ma91AExDeMAZ1rjTjaP8V2A2obQE+s5ltKRwYlwdpArz9xVbp0tF3b0VV2ACNPn
    waline:
      src: webcache|@waline/client@2.15.8/dist/waline.mjs
      integrity: sha384-9sbqJjrfGjbkI6/PI4nU/MvBfEmkkPC4YK9I4zBeMIf1CVCZdCMH/KinBEAZII/5
    twikoo:
      src: webcache|twikoo@1.6.16/dist/twikoo.all.min.js
      integrity: sha384-lDHsr5aZmkMS0eKnsUu6e9RWP+dRmn7sgJw7fuvXBt9W/OChF/Ijx+aUuBDqQwEk
    gitalk:
      src: webcache|gitalk@1.8.0/dist/gitalk.min.js
      integrity: sha384-kspnZUWBoSWwoJHa0hBCXYbHGbhvU/lcEH5O8eVbSDhbPwsiVUTp/aGX/z/5EuMA
    busuanzi:
      src: webcache|busuanzi@2.3.0/bsz.pure.mini.js
      integrity: sha384-0M75wtSkhjIInv4coYlaJU83+OypaRCIq2SukQVQX04eGTCBXJDuWAbJet56id+S
    algolia:
      src: webcache|algoliasearch@4.17.1/dist/algoliasearch-lite.umd.js
      integrity: sha384-xvLS0jfKuoREs7pqkRI/OI8GcqohO5S+jQz7ZBtQXnsXmD+9jDOOY4cL6dCPzlrk
    instantsearch:
      src: webcache|instantsearch.js@4.56.1/dist/instantsearch.production.min.js
      integrity: sha384-hHJCflT4KBLQyHfKO9vpstIcFKn/Y+KHTORelMMEn7mOp2AVPp+7fr03dLgZiV3J
    pace:
      src: webcache|pace-js@1.2.4/pace.min.js
      integrity: sha384-k6YtvFUEIuEFBdrLKJ3YAUbBki333tj1CSUisai5Cswsg9wcLNaPzsTHDswp4Az8
    mermaid:
      src: webcache|mermaid@9.4.3/dist/mermaid.min.js
      integrity: sha384-aG3Gai4tbCHF0iXo48HwLoOZyut7mBl50oMC9GD1m75xyHfJDv6w8hD/kZRD47aJ
    firework:
      src: webcache|mouse-firework@0.1.0/dist/index.umd.js
      integrity: sha384-KM6i7tu43nYd6e0beIljxHMC5tZc58XBDu7pPA58w50h18Jsx7gLdimfS09RXlKv
    pjax:
      src: webcache|theme-shokax-pjax@0.0.3/dist/index.umd.js
      integrity: sha384-xneY1WY8hOfUzswrE4CrYq35N4BdVcxqxwHPr9zawE/jMSCxD+jAPU55x/jj3wlf
    live2d:
      base: fastly_jsdelivr_gh|D-Sketon/plugin-live2d/
      js: fastly_jsdelivr_gh|D-Sketon/plugin-live2d/js/live2d-autoload.js
    live2d_widgets:
      src: webcache|live2d-widgets@0.9.0/autoload.js
      integrity: sha384-poTN7wN/SqNhQqo3jdFeX20ikddWeFGkUkDEzsKjgH/ez8aQLn81oI0Cw6q5xNyB
    md5:
      src: webcache|blueimp-md5@2.19.0/js/md5.min.js
      integrity: sha384-JmVtRz6RWiXnA14QbIOJzPuU3MidULOpBP66deeLLyyoF4Tr/gZlbkHkL6vTthxH
    quicklink:
      src: webcache|quicklink@2.3.0/dist/quicklink.umd.js
      integrity: sha384-aD7FsuQkS1ohgFKY41fJfeA+Wd/RNnrOd9Bs58K3FzKdJJv8yPnYU8Tnp5z1agS
    katex:
      src: webcache|katex@0.16.11/dist/katex.min.js
      integrity: sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg
    katex_auto_render:
      src: webcache|katex@0.16.11/dist/contrib/auto-render.min.js
      integrity: sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeMIf/+rCMvRwr4yROQP43s0Xk
    mathjax:
      src: webcache|mathjax@3.2.2/es5/tex-mml-chtml.js
      integrity: sha384-Wuix6BuhrWbjDBs24bXrjf4ZQ5aFeFWBuKkFekO2t8xFU0iNaLQfp2K6/1Nxveei
    aplayer:
      src: webcache|aplayer@1.10.1/dist/APlayer.min.js
      integrity: sha384-gdGYZwHnfJM54evoZhpO0s6ZF5BQiybkiyW7VXr+h5UfruuRL/aORyw+5+HZoU6e
    meting:
      src: webcache|meting@2.0.1/dist/Meting.min.js
      integrity: sha384-ASVlpKF80A22OXTK3tfEjZm1EL6uFMKIC4p8+0maanw1S/IyB+Y4JG+ZDU7GpKE8
    qrcode:
      src: webcache|qrcode@1.4.4/build/qrcode.min.js
      integrity: sha384-0RsG1yo/crf/1Qc14sho26SXXOTngNCjgJw7fuvXBt9W/OChF/Ijx+aUuBDqQwEk
    html2image:
      src: webcache|html-to-image@1.11.11/dist/html-to-image.js
      integrity: sha384-UbfRVKN3/elS1r7JcK2FhmPP+KlJ4CvYwbyYD7tH+uTkbT9bNJr9eJeQ0FoFbAgz
    dompurify:
      src: webcache|dompurify@3.2.4/dist/purify.min.js
      integrity: sha384-eEu5CTj3qGvu9PdJuS+YlkNi7d2XxQROAFYOr59zgObtlcux1ae1Il3u7jvdCSWu/
  css:
    photoswipe: webcache|photoswipe@5.4.4/dist/photoswipe.css
    katex: webcache|katex@0.16.11/dist/katex.min.css
    waline: webcache|@waline/client@2.15.8/dist/waline.css
    gitalk: webcache|gitalk/dist/gitalk.css
    fontawesome:
      high_priority:
        - webcache|@fortawesome/fontawesome-free@6.5.1/css/regular.min.css
        - webcache|@fortawesome/fontawesome-free@6.5.1/css/solid.min.css
      low_priority:
        - webcache|@fortawesome/fontawesome-free@6.5.1/css/brands.min.css
        - webcache|@fortawesome/fontawesome-free@6.5.1/css/v5-font-face.min.css
        - webcache|@fortawesome/fontawesome-free@6.5.1/css/v4-font-face.min.css
    aos: webcache|@reimujs/aos@0.1.0/dist/aos.css
    aplayer: webcache|aplayer@1.10.1/dist/APlayer.min.css
