# Hexo 配置
## 文件： https://hexo.io/docs/configuration.html
## 原始碼： https://github.com/hexojs/hexo/

# 網站
title: siewilly's Blog
subtitle: 'Coding, Learning, Life'
description: 'Professional Bug Creator'
keywords: 'Hexo, Blog, Coding, Learning, Life'
author: siewilly
language: zh-TW
timezone: 'Asia/Taipei'

url: https://itousouta15.github.io
permalink: :year/:month/:day/:urlname/
permalink_defaults:
pretty_urls:
  trailing_index: true # 設置為 false 以移除網址中的 'index.html'
  trailing_html: true # 設置為 false 以移除網址中的 '.html'

# 目錄
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true 
  field: site 
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# 首頁設置
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分類與標籤
default_category: 未分類
category_map:
tag_map:

# 元數據元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期 / 時間格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# 分頁
per_page: 10
pagination_dir: page

# 包含 / 排除檔案
include:
exclude:
ignore:

# 擴展
theme: reimu

# 部署
## 文件： https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# Clean CSS 配置
## 使用 hexo-clean-css 壓縮 CSS 文件
clean_css:
  exclude: 
    - '*.min.css'

# All Minifier 配置
## 使用 hexo-all-minifier 全面優化 HTML、CSS、JS 和圖片
all_minifier:
  enable: true
  # HTML 壓縮選項
  html:
    enable: true
    exclude: []
  # CSS 壓縮選項  
  css:
    enable: true
    exclude: ['*.min.css']
  # JS 壓縮選項
  js:
    enable: true
    exclude: ['*.min.js']
  # 圖片壓縮選項
  image:
    enable: true
    exclude: []

# 主題配置
theme_config:
  # 動態主題色
  material_theme:
    enable: false

  # 自定義字體
  font:
    article:
      - Mulish
      - Noto Serif SC
    code:
      - JetBrains Mono
  local_font:
    article:
      - "-apple-system"
      - PingFang SC
      - Microsoft YaHei
      - sans-serif
    code:
      - Menlo
      - Monaco
      - Consolas
      - monospace

  # 菜單配置
  menu:
    - name: home
      url: /
      icon:
    - name: portfolio
      url: /portfolio
      icon:
    - name: archives
      url: /archives
      icon:
    - name: about
      url: /about
      icon:
    - name: friend
      url: /friend
      icon:

  # 底部配置
  footer:
    icon: 
      url: "/images/taichi.png"
      rotate: true
      mask: true
      color: "#0000FF" # 確保設置為藍色

  # 回到頂部配置
  top:
    icon: 
      url: "/images/taichi.png"
      rotate: true
      mask: true
      color: "#0000FF" # 確保設置為藍色

  # 贊助配置
  sponsor:
    icon: 
      url: "/images/taichi.png"
      rotate: true
      mask: true
      color: "#0000FF" # 確保設置為藍色

  # 預加載配置
  preloader:
    enable: true
    text: 載入中...
    icon: "/images/taichi.png"
    color: "#0000FF" # 設置為藍色

  # 錨點圖標
  anchor_icon: f292 # 預設使用 '#' 圖標，您可以使用 fontawesome 或 icon_font 的十六進制表示，例如 'f0c1'

  # 滑鼠指針配置
  reimu_cursor:
    enable: true
    cursor:
      default: /img/cursor/1.png
      pointer: /img/cursor/2.png
      text: /img/cursor/3.png

  covers:
    enable: true
    data: source/_data/covers.yml # 確保路徑正確

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

markdown_it_plus:
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix: ''
  linkify: true
  typographer: true
  quotes: '""'''''
  rawLaTeX: false
